### ISSUE TITLE
Using r.URL.Path is better

### ISSUE THREAD

**Issue by ccclin** [ddo/go-vue-handler#1]
Very thanks your source code, it's a pretty good way to deploy Vue.js app with history mode (html5 pushstate) on Google App Engine (GAE).
It's work fine on development mode, however, working failed after deploy on GAE.
The reason is
```
url := r.URL.String()
```
will return full path (like https://host.path/path) on GAE, and the url include the `.` in next code will be true.
Therefore, I suggest to use other method like
```
url := r.URL.Path
```
BTW, I have to say again, it's a pretty good way, thanks boss.

**Comment by ddo** [comment]
thank you very much. done -> https://github.com/ddo/go-vue-handler/commit/5bb651e642775a116ee46b3dba98c52e15d34a62
