### ISSUE TITLE
Does it work with a PWA too?

### ISSUE THREAD

**Issue by dhax** [ddo/go-vue-handler#2]
Have you tried this with a Vue PWA? I had issues serving the service-worker.js file on reloads. The dirty solution below works for me, but I'm sure the os.Stat call is no good at all performance wise...

```
func SPAHandler(publicDir string) http.HandlerFunc {
	handler := http.FileServer(http.Dir(publicDir))
	return func(w http.ResponseWriter, r *http.Request) {
		indexPage := path.Join(publicDir, "index.html")
		serviceWorker := path.Join(publicDir, "service-worker.js")

		requestedAsset := path.Join(publicDir, r.URL.Path)
		if strings.Contains(requestedAsset, "service-worker.js") {
			requestedAsset = serviceWorker
		}
		if _, err := os.Stat(requestedAsset); err != nil {
			http.ServeFile(w, r, indexPage)
			return
		}
		handler.ServeHTTP(w, r)
	}
}
```

**Comment by ddo** [comment]
@dhax i never try PWA yet. Yes if os.Stat is called every request can cause performance trouble. But imo you can cache all the ``requestedAsset`` once it served. For real time you can remove those cache after interval of time.
